watch_stylesheet: true
watch_config: true
debug: false
komorebi:
  start_command: "komorebic start --ahk --masir"
  stop_command: "komorebic stop --ahk --masir"
  reload_command: "komorebic stop --ahk --masir && komorebic start --ahk --masir"
bars:
  primary-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: false
      acrylic: false
      dark_mode: false
      round_corners: false
      border_color: None
    window_flags:
      windows_app_bar: false
      auto_hide: true
      always_on_top: true
    dimensions:
      width: "100%"
      height: 28
    widgets:
      left: ["komorebi_workspaces", "komorebi_active_layout", "media", "systray"]
      center: ["active_window"]
      right: ["taskbar", "volume", "battery", "power_menu"]
widgets:
  # language:
  #   type: "yasb.language.LanguageWidget"
  #   options:
  #     label: "<span>\uf11c</span>{lang[country_code]}"
  #     update_interval: 5
  #     callbacks:
  #       on_left: "toggle_menu"
  #       on_middle: "do_nothing"
  #       on_right: "do_nothing"
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_alt: "[class_name='{win[class_name]}' exe='{win[process][name]}' hwnd={win[hwnd]}]"
      label_no_window: ""
      label_icon: true
      label_icon_size: 14
      max_length: 56
      max_length_ellipsis: "..."
      monitor_exclusive: true
      callbacks:
        on_left: "do_nothing"
        on_middle: "do_nothing"
        on_right: "do_nothing"
  komorebi_workspaces:
    type: "komorebi.workspaces.WorkspaceWidget"
    options:
      label_offline: "\u26a1 Offline"
      label_workspace_btn: ""
      label_workspace_active_btn: ""
      label_workspace_populated_btn: ""
      label_default_name: "{index}"
      label_zero_index: false
      hide_empty_workspaces: false
      hide_if_offline: false
      animation: false
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{volume}"
      volume_icons:
        - "\ueee8" # Icon for muted
        - "\uf026" # Icon for 0-10% volume
        - "\uf027" # Icon for 11-30% volume
        - "\uf027" # Icon for 31-60% volume
        - "\uf028" # Icon for 61-100% volume
      callbacks:
        on_left: "toggle_volume_menu"
        on_right: "exec cmd.exe /c start ms-settings:sound"
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "<span>\uf011</span>"
      uptime: True
      blur: False
      blur_background: True
      animation_duration: 200 # Milisecond
      button_row: 5 # Number of buttons in row, min 1 max 5
      buttons:
        shutdown: ["\uf011", "Shut Down"]
        restart: ["\uead2", "Restart"]
        signout: ["\udb80\udf43", "Sign out"]
        hibernate: ["\uf28e", "Hibernate"]
        sleep: ["\u23fe", "Sleep"]
        cancel: ["", "Cancel"]
  taskbar:
    type: "yasb.taskbar.TaskbarWidget"
    options:
      animation:
        enabled: true
      icon_size: 14
      ignore_apps:
        processes: []
        titles: []
        classes: []
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
  win_button:
    type: "yasb.custom.CustomWidget"
    options:
      label: "<span>\udb80\udf5c</span>"
      label_alt: "<span>\udb80\udf5c</span>"
      class_name: "win-btn"
      callbacks:
        # on_left: "exec start_menu"
        on_left: "exec wt.exe"
  battery:
    type: "yasb.battery.BatteryWidget"
    options:
      label: "<span>{icon}</span> {percent}%"
      label_alt: "<span>{icon}</span> {percent}% | time: {time_remaining}"
      update_interval: 5000
      time_remaining_natural: False
      hide_unsupported: True
      charging_options:
        icon_format: "{charging_icon}"
        blink_charging_icon: true
        blink_interval: 500
      status_thresholds:
        critical: 10
        low: 25
        medium: 75
        high: 95
        full: 100
      status_icons:
        icon_charging: "\uf0e7"
        icon_critical: "\uf244"
        icon_low: "\uf243"
        icon_medium: "\uf242"
        icon_high: "\uf241"
        icon_full: "\uf240"
  # cpu:
  #   type: "yasb.cpu.CpuWidget"
  #   options:
  #     label: "<span>\uf4bc</span> {info[percent][total]}%"
  #     label_alt: "<span>\uf437</span> {info[histograms][cpu_percent]}"
  #     update_interval: 2000
  #     histogram_icons:
  #       - '\u2581' # 0%
  #       - '\u2581' # 10%
  #       - '\u2582' # 20%
  #       - '\u2583' # 30%
  #       - '\u2584' # 40%
  #       - '\u2585' # 50%
  #       - '\u2586' # 60%
  #       - '\u2587' # 70%
  #       - '\u2588' # 80%+
  #     histogram_num_columns: 8
  #     callbacks:
  #       on_right: "exec cmd /c Taskmgr"
  # memory:
  #   type: "yasb.memory.MemoryWidget"
  #   options:
  #     label: "<span>\uf4bc</span> {virtual_mem_free}/{virtual_mem_total}"
  #     label_alt: "<span>\uf4bc</span> VIRT: {virtual_mem_percent}% SWAP: {swap_mem_percent}%"
  #     update_interval: 5000
  #     callbacks:
  #       on_left: "toggle_label"
  #       on_middle: "do_nothing"
  #       on_right: "do_nothing"
  #     memory_thresholds:
  #       low: 25
  #       medium: 50
  #       high: 90
  wallpapers:
    type: "yasb.wallpapers.WallpapersWidget"
    options:
      label: "<span>\udb83\ude09</span>"
      image_path: "C:\\Users\\chloe\\Pictures\\Backgrounds\\Mountain" # Example path to folder with images
      change_automatically: false # Automatically change wallpaper
      update_interval: 60 # If change_automatically is true, update interval in seconds
      gallery:
          enabled: true
          blur: true
          image_width: 220
          image_per_page: 5
          show_buttons: false
          orientation: "portrait"
          image_spacing: 8
          lazy_load: true
          lazy_load_delay: 80
          lazy_load_fadein: 400
          image_corner_radius: 20
          enable_cache: true
      run_after: # List of functions to run after wallpaper is updated
        
        # - "wt.exe pwsh -noe -Command 'Update-WalTheme -Image {image} -Backend wal'" # Example command to run after wallpaper is updated
        # - "Update-WalTheme -Image {image} -Backend wal" # Example command to run after wallpaper is updated
        # - "cmd.exe /c "
        - "cmd.exe /c start /min pwsh C:/Users/chloe/yasb.ps1" # Example command to run after wallpaper is updated
      # label_shadow:
      #   enabled: true
      #   color: "black"
      #   radius: 3
      #   offset: [ 1, 1 ]

  media:
      type: "yasb.media.MediaWidget"
      options:
        label: "{title}"
        label_alt: "{artist}"
        callbacks:
          on_left: "toggle_media_menu"
          on_middle: "do_nothing"
          on_right: "toggle_label"
        max_field_size:
          label: 25
          label_alt: 25
        show_thumbnail: true
        controls_hide: false
        hide_empty: true
        thumbnail_alpha: 80
        thumbnail_padding: 8
        thumbnail_corner_radius: 6
        icons:
          prev_track: "\ue892"
          next_track: "\ue893"
          play: "\ue768"
          pause: "\ue769"
  systray:
    type: "yasb.systray.SystrayWidget"
    options:
      class_name: "systray"
      label_collapsed: "▼"
      label_expanded: "▶"
      label_position: "left" # Can be "left" or "right"
      icon_size: 16 # Can be any integer between 8 and 64
      pin_click_modifier: "alt" # Can be "ctrl", "alt" or "shift"
      show_unpinned: true
      show_unpinned_button: true
      show_battery: false
      show_volume: false
      show_network: false
      container_padding:
          left: 0
          top: 0
          right: 0
          bottom: 0

  komorebi_active_layout:
    type: "komorebi.active_layout.ActiveLayoutWidget"
    options:
      hide_if_offline: true
      label: "{icon} "
      layouts: ['bsp', 'columns', 'rows', 'grid', 'vertical_stack', 'horizontal_stack', 'ultrawide_vertical_stack','right_main_vertical_stack']
      layout_icons:
        bsp: "\uebeb"
        columns: "\uebf7"
        rows: "\uec01"
        grid: "\udb81\udf58"
        # scrolling: "\uebf7"
        vertical_stack: "\uebee"
        horizontal_stack: "\uebf0"
        ultrawide_vertical_stack: "\uebee"
        right_main_vertical_stack: "\uebf1"
        monocle: "\uf06f"
        maximised: "\uf06f"
        floating: "\uf2d2"
        paused: "\udb83\udf89"
        tiling: "\udb81\ude40"
      callbacks:
        on_left: 'toggle_layout_menu'
        on_middle: 'next_layout'
        on_right: 'prev_layout'
      layout_menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "System"
        alignment: "left"
        direction: "down"
        offset_top: 6
        offset_left: 0
        show_layout_icons: true
      # container_padding: 
      #   top: 0
      #   left: 8
      #   bottom: 0
      #   right: 8